sudo: false
language: node_js
node_js:
- 5.1.1
script:
- npm run travis
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && codeclimate-test-reporter < ./coverage/lcov.info || true'
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && ./scripts/checkPullRequest.js'
notifications:
  slack:
    secure: MPEurDUvYfcl3b5Hji/42sKF6TQLRcrkqMfKINy6buFePKdbkwDjQd+r0GYAC153lLpbJeiFy7p8TAVp2QP3wmC02ea9n3CG8juKpCBabyaZq3RBvhJ7kKUd/BdTLPNWU1ttSrQlzOoAs3HcuEAaeUzhW3d0LPH+bVvYx4aG8UM=
env:
  global:
  - secure: dczgNmycwYw9E7aAQN+/Ad/l93SIWTPDCnJ39eLWb0Wwp4CdvNAfdt9EV9ysQSba5ylaD7I1dD6nmFkZla1m8UtxdrPbTm/gf0v40ZXgSErxkFpRt+cj442j6v/IqFi9Ok78KwVpeyUjraWD5HToCwBI9BxtpoqrCVh84DfplSo=
  - secure: MIs4tujO4ZvqHcD8+zjn7mum01kN76mj4ZtkCDJmHgr6t4TOLRnws93veTz1nMpvUHRN+yr32f4abEFmK1VuSfZwg8Vs/fQ2Pboy5EGKX4vXSKciMr35h+HdMnoNyUPSr5Cex+7S9B7c/cpDqoAKNpc/s4KS5WnVMue5NOagfee4kba6SvEAghdtlK6gGeyCb4DXK+SuhtFOlO/No5xkni0+f8tlsr1oaqzJsecRMOFDO5b3d5TagGpdyzCUw6q/LLkMwmwXT1soxzsecIA/TbEZ4MVPgMJR8BcKVzwOzhBmLWtbzS5FTjFtBcrONnc0R8aAs+220ofWS5jXqVThlrMAsSko/QPJdPlxZ03k9qX7Z7me+H8OLDCkdtSuD7eHTfAM+k05oB9S1TJE62Tpf6DbYIuGyoawshA4p0/Ox1t698qkI3wTEDK6xAfRp6fHqNfdcGBFj10G9m8P7uOipydFiTCr+cg/sGHrKJZjVYblmEcYw16pTX7HsI88Gu+CjknWGUToqV/fjtrZluBpPhdw8ae3a/rT38JuupCO0ib9xlZn7u2fWaO1EoSINvXCKGfWqusnXzzn0L71L2WFUNlmjy9ZbOuhjUnLblv989Bs/IIA/xZjJR1/D1lwjx2EoGKLE1mSPUdmXwhSCo06Y6I0Wr1h+QGL1lhmFbfLISo=
